-- AlterTable
ALTER TABLE "User" ADD COLUMN "lastKnownLat" DOUBLE PRECISION;
ALTER TABLE "User" ADD COLUMN "lastKnownLng" DOUBLE PRECISION;
ALTER TABLE "User" ADD COLUMN "lastKnownAccuracy" DOUBLE PRECISION;
ALTER TABLE "User" ADD COLUMN "lastKnownAt" TIMESTAMP(3);
